### DISCUSSION TITLE
Unspecified colors in default face

### DISCUSSION THREAD

**Discussion by togakangaroo** [minad/org-modern#287] [Q&A]
I'm not 100% sure if this is actually a bug with `org-modern`, spacemacs, or its interaction with my setup, I haven't dug down that far. I *am* pretty sure that some aspect of it is on spacemacs' side, but I think yall should also be aware - I [created an issue here](https://github.com/syl20bnr/spacemacs/issues/17008). It might be something really obvious for someone who is familiar with the org-modern codebase.

**Comment by minad** [comment]
I haven't observed such problems with org-modern. Please try to reproduce with emacs -Q first, and not with spacemacs.

**Comment by jdtsmith** [comment]
The problem is the `unspecified` `:color` in the `:box` attribute.  See #288 for a possible fix (@togakangaroo give that a try).

**Reply by minad** [reply]
Sure, but why does this happen? How can the default face be unspecified. I don't see a reason to add a workaround here until we understand why it happens.

**Reply by jdtsmith** [reply]
The default background color can be, but `:box` color cannot?

**Reply by minad** [reply]
Yes, true. But my point is that I am wondering why the default face colors become suddenly unspecified. I mean the assumption that we can use the face attribute like this has been here for a long time. What has changed? Maybe the assumption was wrong all along, but I'd like to understand this first and check the reason.

**Reply by minad** [reply]
I looked a little bit into this, and I think not setting the box color is not an option, as in your #288. This will lead to incorrectly displayed labels with black borders on light themes. What we need is a reliable way to get the background color of the frame. My assumption has always been that the default face would give me that. 🤷🏾

**Reply by minad** [reply]
> C-h f face-attribute

tells me this

> To ensure that the return value is always specified and absolute, use a
value of default for INHERIT; this will resolve any unspecified or
relative values by merging with the **default face** (**which is always
completely specified**).

IOW this is a bug in spacemacs.

**Reply by jdtsmith** [reply]
Yeah, I agree it's strange.

**Reply by jdtsmith** [reply]
I've relied on that INHERIT comment myself many times.  On the other hand, my `default` face has `DistantForeground: unspecified`, so it's not apparently _absolute_.  Perhaps this is just a convention that is sometimes ignored.

**Reply by minad** [reply]
I think distant-foreground is just an alternative to foreground used instead of foreground if foreground and background are too similar, and if available. Anyway, I don't think org-modern should be changed here. It is not good if assumptions are gradually weakened as we go. I want Emacs to be a stable platform, and this means that I am sticking to assumptions which are reasonable and have been valid for a long time.

**Reply by jdtsmith** [reply]
That's fair.  `:background` in particular seems essential for a default face to have; @togakangaroo, see if you can determine why your `default` face has an unspecified background.

**Reply by togakangaroo** [reply]
Hi, sorry for disappearing for a bit. Honestly, font faces is one of the parts of emacs that I still have very poor understanding of so I can't really speak to it. 

Taking a guess at some things I can say that might be useful this side of studying up on font faces and what spacemacs does with them. I have the following configuration:

```
   dotspacemacs-default-font '("Source Code Pro"
                               :size 11.0
                               :weight normal
                               :width normal)
```
this is my `describe-face`
```
Face: default (sample) (customize this face)

Documentation:
Basic default face.

Defined in ‘faces.el’.


           Family: Source Code Pro
          Foundry: ADBO
            Width: normal
           Height: 113
           Weight: regular
            Slant: normal
       Foreground: #b2b2b2
DistantForeground: unspecified
       Background: #292b2e
        Underline: nil
         Overline: nil
   Strike-through: nil
              Box: nil
          Inverse: nil
          Stipple: nil
             Font: #<font-object -ADBO-Source Code Pro-regular-normal-normal-*-15-*-*-*-m-0-iso10646-1>
          Fontset: -ADBO-Source Code Pro-regular-normal-normal-*-15-*-*-*-m-0-fontset-auto2
           Extend: nil
          Inherit: nil
```
and running this does indeed result a value
```
#+begin_src emacs-lisp :results code
   (face-attribute 'default :background nil t)
#+end_src

#+RESULTS:
#+begin_src emacs-lisp
"#292b2e"
#+end_src
```

If the issue was that it was unspecified, it might be one of timing?

I can recreate the issue by toggling org-modern on and off by setting `(setq-default org-enable-modern-support 't)` and in both versions I have the same describe-face as above

If yall see anything that you could direct me to further I'd be happy to poke around more
